Algoritmo "Pagina25exercicioL"
// Disciplina : Lógica de Programação
// Professor  : Jailson Costa dos Santos
// Descrição  : Quadrado de 3 numeros
// Autor(a)   : Luana Rocha Miron
// Data atual : 17/09/2025
Var
// Seção de Declarações das variáveis 
numero1, numero2, numero3, quadrado : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("Digite o valor de A: ")
   leia(numero1)

   escreva("Digite o valor de B: ")
   leia(numero2)

   escreva("Digite o valor de C: ")
   leia(numero3)

   quadrado<- (numero1*numero1) + (numero2*numero2) + (numero3*numero3)

   escreva("A soma dos quadrados é: ", quadrado)
Fimalgoritmo