Algoritmo "Pagina25exercicioM"
// Disciplina : Lógica de Programação
// Professor  : Jailson Costa dos Santos
// Descrição  : Soma do numero de 3 quadrado
// Autor(a)   : Luana Rocha Miron
// Data atual : 17/09/2025
Var
// Seção de Declarações das variáveis 
 numero1, numero2, numero3, quadrado : inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("Digite o valor de A: ")
   leia(numero1)

   escreva("Digite o valor de B: ")
   leia(numero2)

   escreva("Digite o valor de C: ")
   leia(numero3)

   quadrado<- numero1+numero2+numero3
   quadrado<- quadrado*quadrado

   escreva("O quadrado da soma dos valores é: ", quadrado)
Fimalgoritmo