Algoritmo "Pagina46exercicioH"
// Disciplina : Lógica de Programação
// Professor  : Jailson Costa dos Santos
// Descrição  :  Conversão de celcius para fahreheint
// Autor(a)   : Luana Rocha Miron
// Data atual : 17/09/2025

Var
// Seção de Declarações das variáveis 
 Celsius, Fahrenheit : real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  Celsius <-10
  
   enquanto (Celsius <110) faca
   Fahrenheit <- ((9 * Celsius) + 160) /5
   Escreval(Celsius, " °C = ", Fahrenheit, " °F")
   Celsius<- Celsius + 10
   fimenquanto

Fimalgoritmo