Algoritmo "Pagina25exercicioB"
// Disciplina : Lógica de Programação
// Professor  : Jailson Costa dos Santos
// Descrição  : Converter temperatura de F para C
// Autor(a)   : Luana Rocha Miron
// Data atual : 17/09/2025
Var
// Seção de Declarações das variáveis 
 Celsius, Fahrenheit : real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("Digite a temperatura em Fahrenheit")
    leia(Fahrenheit)

    Celsius <- (Fahrenheit-32)*(5/9)

    Escreval(Fahrenheit, "°F é ", Celsius, " °C")
Fimalgoritmo