Algoritmo "Pagina26exercicioA"
// Disciplina : Lógica de Programação
// Professor  : Jailson Costa dos Santos
// Descrição  : Programa de computador
// Autor(a)   : Luana Rocha Miron
// Data atual : 17/09/2025
Var
// Seção de Declarações das variáveis 
a, b, c, d, produto, soma: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("Digite o valor de A: ")
   leia(a)

   escreva("Digite o valor de B: ")
   leia(b)

   escreva("Digite o valor de C: ")
   leia(c)

   escreva("Digite o valor de D: ")
   leia(d)

   produto <- a*c
   soma<- b+d


   escreval("Produto de A e C : ", produto)
   escreval("Soma de B e D : ", soma)

Fimalgoritmo