Algoritmo "Pagina66exercicioE"
// Disciplina : Lógica de Programação
// Professor  : Jailson Costa dos Santos
// Descrição  : Mostrar os impares entre 0 de 20
// Autor(a)   : Luana Rocha Miron
// Data atual : 17/09/2025
Var
// Seção de Declarações das variáveis 
 i : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para i de 1 ate 20 passo 1 faca
      se i mod 2 = 1 entao
         escreva(i, " ")
         i<- i+1
      senao
         i<- i+1
      fimse
   fimpara


Fimalgoritmo