Algoritmo "Pagina25exercicioG"
// Disciplina : Lógica de Programação
// Professor  : Jailson Costa dos Santos
// Descrição  : Seis operações
// Autor(a)   : Luana Rocha Miron
// Data atual : 17/09/2025
Var
// Seção de Declarações das variáveis 
 a, b, c, d, resultado : inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("Valor a ser armazenado em A: ")
   leia(a)

   escreval("Valor a ser armazenado em B: ")
   leia(b)

   escreval("Valor a ser armazenado em C: ")
   leia(c)

   escreval("Valor a ser armazenado em D: ")
   leia(d)

   resultado <- A + B
   escreval("Valor de A+B: ", resultado)

   resultado <- A * B
   escreval("Valor de AxB: ", resultado)

   resultado <- A + C
   escreval("Valor de A+C: ", resultado)

   resultado <- A * C
   escreval("Valor de AxC: ", resultado)

   resultado <- A + D
   escreval("Valor de A+D: ", resultado)

   resultado <- A * D
   escreval("Valor de AxD: ", resultado)

   resultado <- B + C
   escreval("Valor de B+C: ", resultado)

   resultado <- B * C
   escreval("Valor de BxC: ", resultado)

   resultado <- B + D
   escreval("Valor de B+D: ", resultado)

   resultado <- B * C
   escreval("Valor de B*D: ", resultado)

   resultado <- C + D
   escreval("Valor de C+D: ", resultado)

   resultado <- C * D
   escreval("Valor de CxD: ", resultado)
Fimalgoritmo