Algoritmo "Pagina25exercicioA"
// Disciplina : Lógica de Programação
// Professor  : Jailson Costa dos Santos
// Descrição  : Converter temperatura
// Autor(a)   : Luana Rocha Miron
// Data atual : 17/09/2025
Var
   // Seção de Declarações das variáveis
   Celsius, Fahrenheit : real
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite a temperatura em Celsius")
   leia(Celsius)

   Fahrenheit <- ((9*Celsius)+160) /5

   Escreval(Celsius, "°C é ", Fahrenheit, " °F")
Fimalgoritmo