Algoritmo "Pagina66exercicioC"
// Disciplina : Lógica de Programação
// Professor  : Jailson Costa dos Santos
// Descrição  : Soma dos 100 primeiros numeros
// Autor(a)   : Luana Rocha Miron
// Data atual : 17/09/2025
Var
// Seção de Declarações das variáveis 
 i, soma : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para i de 1 ate 100 passo 1 faca
      soma <- soma + i
      i<- i+1
   fimpara

   escreva("Total: ", soma)

Fimalgoritmo