Algoritmo "Pagina41exercicioI"
// Disciplina : Lógica de Programação
// Professor  : Jailson Costa dos Santos
// Descrição  : Impar ou par
// Autor(a)   : Luana Rocha Miron
// Data atual : 17/09/2025
Var
   // Seção de Declarações das variáveis
   valor : inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva("Digite o valor: ")
   Leia(valor)

   se valor mod 2 = 0  entao
      escreval("Par")
   senao
      escreval("Ímpar")
   fimse

Fimalgoritmo