Algoritmo "Quadrado15a200"
// Disciplina : Lógica de Programação
// Professor  : Jailson Costa dos Santos
// Descrição  : Calcular o quadrado dos numeros de 15 a 200
// Autor(a)   : Luana Rocha Miron
// Data atual : 17/09/2025
Var
   // Seção de Declarações das variáveis
   contadora,resultado: inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para contadora de 15 ate 200 passo 1 faca
      resultado <- contadora * contadora
      Escreval("O quadrado de ", contadora, " é igual: ",resultado)
   fimpara
Fimalgoritmo